### ISSUE TITLE
DateTimeBuilder Focus traversal corrupted

### ISSUE THREAD

**Issue by fiurthorn** [GiancarloCode/form_bloc#297]
Hi, 

i have some Focus Traversal Problems with the DateTime Builder.

1. you have to use `nextFocusNode` and `focusNode` to set the Focus to the next element, after choose a date.
2. after a second round next to the `DateTimeBuilder`, a Tabulator produces following error:

```
The following assertion was thrown while processing the key message handler:
Tried to get the bounds of a focus node that didn't have its context set yet.
```

removing the DateTimeBuilder solves the Problem. 

<details>
<summary>full error</summary>

```
Restarted application in 727ms.

════════ Exception caught by services library ══════════════════════════════════
The following assertion was thrown while processing the key message handler:
Tried to get the bounds of a focus node that didn't have its context set yet.
The context needs to be set before trying to evaluate traversal policies. Setting the context is typically done with the attach method.
'package:flutter/src/widgets/focus_manager.dart':
Failed assertion: line 729 pos 7: 'context != null'


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=2_bug.md

When the exception was thrown, this was the stack
#2      FocusNode.rect
#3      new _ReadingOrderSortData
#4      ReadingOrderTraversalPolicy.sortDescendants
#5      FocusTraversalPolicy._sortAllDescendants
#6      FocusTraversalPolicy._moveFocus
#7      FocusTraversalPolicy.next
#8      FocusNode.nextFocus
#9      NextFocusAction.invoke
#10     ActionDispatcher.invokeAction
#11     ShortcutManager.handleKeypress
#12     _ShortcutsState._handleOnKey
#13     FocusManager._handleKeyMessage
#14     KeyEventManager.handleRawKeyMessage
#15     BasicMessageChannel.setMessageHandler.<anonymous closure>
#16     BasicMessageChannel.setMessageHandler.<anonymous closure>
#17     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
#18     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure>
#19     _invoke2.<anonymous closure> (dart:ui/hooks.dart:190:15)
#23     _invoke2 (dart:ui/hooks.dart:189:10)
#24     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:42:5)
#25     _Channel.push (dart:ui/channel_buffers.dart:132:31)
#26     ChannelBuffers.push (dart:ui/channel_buffers.dart:329:17)
#27     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:583:22)
#28     _dispatchPlatformMessage (dart:ui/hooks.dart:89:31)
(elided 5 frames from class _AssertionError and dart:async)
KeyMessage: KeyMessage([KeyDownEvent#90477(physicalKey: PhysicalKeyboardKey#7002b(usbHidUsage: "0x0007002b", debugName: "Tab"), logicalKey: LogicalKeyboardKey#00009(keyId: "0x100000009", keyLabel: "Tab", debugName: "Tab"), character: "	", timeStamp: 50:01:59.255000)])
════════════════════════════════════════════════════════════════════════════════
```

</details>

<details>
<summary>example.dart</summary>

```dart
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutter_form_bloc/flutter_form_bloc.dart';

void main() => runApp(const App());

class App extends StatelessWidget {
  const App({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      theme: ThemeData.light(),
      home: const ListFieldsForm(),
    );
  }
}

class ListFieldFormBloc extends FormBloc<String, String> {
  final clubName = TextFieldBloc(name: 'clubName');
  final clubFullName = TextFieldBloc(name: 'clubFullName');
  final createTime = InputFieldBloc<DateTime?, Object>(initialValue: DateTime.now());

  ListFieldFormBloc() {
    addFieldBlocs(
      fieldBlocs: [
        clubName,
        clubFullName,
        createTime,
      ],
    );
  }

  @override
  void onSubmitting() async {
    // Without serialization
    final clubV1 = Club(
      clubName: clubName.value,
    );

    print('clubV1');
    print(clubV1);

    // With Serialization
    final clubV2 = Club.fromJson(state.toJson());

    ('clubV2');
    print(clubV2);

    emitSuccess(
      canSubmitAgain: true,
      successResponse: const JsonEncoder.withIndent('    ').convert(
        state.toJson(),
      ),
    );
  }
}

class Club {
  String? clubName;
  String? clubFullName;
  DateTime? creation;

  Club({this.clubName, this.creation});

  Club.fromJson(Map<String, dynamic> json) {
    clubName = json['clubName'];
    clubFullName = json['clubFullName'];
    creation = json['creation'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['clubFullName'] = clubFullName;
    data['clubName'] = clubName;
    return data;
  }

  @override
  String toString() => toJson().toString();
}

class ListFieldsForm extends StatelessWidget {
  const ListFieldsForm({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return BlocProvider(
      create: (context) => ListFieldFormBloc(),
      child: Builder(
        builder: (context) {
          final formBloc = context.read<ListFieldFormBloc>();
          final next = FocusNode();
          return Scaffold(
            resizeToAvoidBottomInset: false,
            appBar: AppBar(title: const Text('List and Group Fields')),
            floatingActionButton: FloatingActionButton(
              onPressed: formBloc.submit,
              child: const Icon(Icons.send),
            ),
            body: FormBlocListener<ListFieldFormBloc, String, String>(
              onSubmitting: (context, state) {
                //   LoadingDialog.show(context);
              },
              onSuccess: (context, state) {
                //   LoadingDialog.hide(context);
                ScaffoldMessenger.of(context).showSnackBar(SnackBar(
                  content: SingleChildScrollView(child: Text(state.successResponse!)),
                  duration: const Duration(milliseconds: 1500),
                ));
              },
              onFailure: (context, state) {
                //   LoadingDialog.hide(context);
                ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text(state.failureResponse!)));
              },
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: <Widget>[
                  TextFieldBlocBuilder(
                    autofocus: true,
                    textFieldBloc: formBloc.clubName,
                    decoration: const InputDecoration(
                      labelText: 'Club Name',
                      prefixIcon: Icon(Icons.sentiment_satisfied),
                    ),
                  ),
                  DateTimeFieldBlocBuilder(
                    dateTimeFieldBloc: formBloc.createTime,
                    decoration: const InputDecoration(
                      prefixIcon: Icon(Icons.sentiment_dissatisfied),
                      labelText: "creation",
                    ),
                    format: DateFormat('dd-MM-yyyy'),
                    initialDate: DateTime.now().add(const Duration(days: 1)),
                    firstDate: DateTime(2022, 1, 1),
                    lastDate: DateTime(2032, 31, 12),
                    nextFocusNode: next,
                  ),
                  TextFieldBlocBuilder(
                    focusNode: next,
                    textFieldBloc: formBloc.clubFullName,
                    decoration: const InputDecoration(
                      labelText: 'Club Full Name',
                      prefixIcon: Icon(Icons.sentiment_satisfied),
                    ),
                  ),
                ],
              ),
            ),
          );
        },
      ),
    );
  }
}

class LoadingDialog extends StatelessWidget {
  static void show(BuildContext context, {Key? key}) => showDialog<void>(
        context: context,
        useRootNavigator: false,
        barrierDismissible: false,
        builder: (_) => LoadingDialog(key: key),
      ).then((_) => FocusScope.of(context).requestFocus(FocusNode()));

  static void hide(BuildContext context) => Navigator.pop(context);

  const LoadingDialog({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
      onWillPop: () async => false,
      child: Center(
        child: Card(
          child: Container(
            width: 80,
            height: 80,
            padding: const EdgeInsets.all(12.0),
            child: const CircularProgressIndicator(),
          ),
        ),
      ),
    );
  }
}

class SuccessScreen extends StatelessWidget {
  const SuccessScreen({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            const Icon(Icons.tag_faces, size: 100),
            const SizedBox(height: 10),
            const Text(
              'Success',
              style: TextStyle(fontSize: 54, color: Colors.black),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 10),
            ElevatedButton.icon(
              onPressed: () =>
                  Navigator.of(context).pushReplacement(MaterialPageRoute(builder: (_) => const ListFieldsForm())),
              icon: const Icon(Icons.replay),
              label: const Text('AGAIN'),
            ),
          ],
        ),
      ),
    );
  }
}
```

</details>

**Comment by HelenBo** [comment]
I have the same issue. @fiurthorn Did you find a solution?

**Comment by fiurthorn** [comment]
> I have the same issue. @fiurthorn Did you find a solution?

unfortunately I haven't found a solution yet.

**Comment by fiurthorn** [comment]
fixed it by implement a custom datetime builder w/o spawning a datetime dialog on the focus event.

**Comment by GiancarloCode** [comment]
> fixed it by implement a custom datetime builder w/o spawning a datetime dialog on the focus event.

Hello, I am currently working on a new version of form_bloc with big changes to its core, I would like to know if there is anything you would like to see added or changed.

Thank you

**Comment by fiurthorn** [comment]
That's my solution:

```dart
class DateTimeSuffixButton extends StatelessWidget {
  final DateTime? firstDateTime;
  final Duration? lastDateDuration;
  final void Function(DateTime?) onSubmit;
  final DateTime? Function() initialDateTime;

  const DateTimeSuffixButton({
    required this.onSubmit,
    required this.initialDateTime,
    this.firstDateTime,
    this.lastDateDuration,
    super.key,
  });

  @override
  Widget build(BuildContext context) => IconButton(
        icon: const Icon(Icons.date_range),
        onPressed: () {
          showDatePicker(
            context: context,
            initialDate: initialDateTime() ?? DateTime.now(),
            firstDate: firstDateTime ?? DateTime.now(),
            lastDate: firstDateTime ?? DateTime.now().add(lastDateDuration ?? const Duration(days: 3653)),
          ).then(onSubmit);
        },
      );
}

class DateTimeBlocBuilder extends TextFieldBlocBuilder {
  DateTimeBlocBuilder({
    super.key,
    bool requestFocus = false,
    DateTime? firstDateTime,
    Duration? lastDateDuration,
    required DateTimeBloc<FieldEntity> bloc,
  }) : super(
          textFieldBloc: bloc,
          autofocus: requestFocus,
          keyboardType: const TextInputType.numberWithOptions(decimal: true),
          inputFormatters: [FilteringTextInputFormatter.allow(RegExp(r"[-/0-9.]"))],
          isEnabled: !bloc.state.extraData!.readyOnly,
          decoration: InputDecoration(
            labelText: bloc.state.extraData!.label.label,
            // hintText: bloc.format.pattern,
            suffixIcon: Focus(
              descendantsAreFocusable: false,
              descendantsAreTraversable: false,
              canRequestFocus: false,
              child: DateTimeSuffixButton(
                initialDateTime: () => bloc.dateTime?.dt,
                firstDateTime: firstDateTime,
                lastDateDuration: lastDateDuration,
                onSubmit: bloc.updateDateTimeValue,
              ),
            ),
          ),
        );
}
```

**Comment by fiurthorn** [comment]
@GiancarloCode i am very satisfied with `form_bloc` and use it actively in my projects.
Apart from this beahavior I have no complaints.

Is there a stand that I can test and give feedback?

**Comment by GiancarloCode** [comment]
@fiurthorn  Thanks, in a few days I will publish a beta version in pub and a new branch, and if you want you can give your feedback.
Happy afternoon :)

**Comment by fiurthorn** [comment]
is there something to test?

**Comment by fiurthorn** [comment]
@GiancarloCode what did you mean with a few days?
